version: '3.8'

services:
  # Backend Service
  habitup-backend:
    build:
      context: ./HabitUPMigration247-master
      dockerfile: Dockerfile
    container_name: habitup-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - USE_MOCK_DB=true
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=docker_jwt_secret_key_for_development
      - JWT_EXPIRES_IN=24h
      - EMAIL_HOST=localhost
      - EMAIL_PORT=587
      - EMAIL_USER=test@test.com
      - EMAIL_PASS=testpass
      - RAZORPAY_KEY_ID=test_key_id
      - RAZORPAY_KEY_SECRET=test_key_secret
      - MAX_FILE_SIZE=10MB
      - UPLOAD_PATH=./uploads
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=1000
    volumes:
      - ./HabitUPMigration247-master/uploads:/app/uploads
    networks:
      - habitup-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  habitup-frontend:
    build:
      context: ./HabitUP-master/HabitUP-master
      dockerfile: Dockerfile
    container_name: habitup-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_USE_REAL_API=true
      - VITE_WEBSOCKET_URL=ws://localhost:3001
      - VITE_API_TIMEOUT=30000
    depends_on:
      habitup-backend:
        condition: service_healthy
    networks:
      - habitup-network

networks:
  habitup-network:
    driver: bridge

volumes:
  uploads-data:
